api:
  fallbackFortune: "Hard times are in front of you: APIs are not responding!"
  apiURL: //fortune-api
service:
  fallbackFortune: "Your future is bright. Live long and prosper!"
  serviceURL: //fortune-service
url:
  apiURL: http://pivot-mbrodi-fortune-api.apps.pcfone.io
  uiURL: http://pivot-mbrodi-fortune-api.apps.pcfone.io
ui:
  fallbackFortune: "Look at you, awesome!"
  apiURL: //fortune-api
